//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace test
{
    using System;
    using System.Collections.Generic;
    
    public partial class Answer
    {
        public int ans_ID { get; set; }
        public Nullable<int> at_ID { get; set; }
        public Nullable<int> rec_ID { get; set; }
        public string ans_grades { get; set; }
        public Nullable<bool> ans_pass { get; set; }
        public string ans_details { get; set; }
    
        public virtual app_test app_test { get; set; }
        public virtual Recruiter Recruiter { get; set; }
    }
}
