//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace test
{
    using System;
    using System.Collections.Generic;
    
    public partial class ap_evaluate
    {
        public int ev_ID { get; set; }
        public string ev_notes { get; set; }
        public Nullable<int> rec_ID { get; set; }
        public Nullable<int> app_ID { get; set; }
        public Nullable<bool> ev_HIRED { get; set; }
    
        public virtual application_ application_ { get; set; }
        public virtual Recruiter Recruiter { get; set; }
    }
}
