//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace test
{
    using System;
    using System.Collections.Generic;
    
    public partial class app_test
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public app_test()
        {
            this.Answers = new HashSet<Answer>();
        }
    
        public int at_ID { get; set; }
        public Nullable<int> t_ID { get; set; }
        public Nullable<int> app_ID { get; set; }
        public Nullable<System.DateTime> at_start { get; set; }
        public Nullable<System.DateTime> at_end { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Answer> Answers { get; set; }
        public virtual application_ application_ { get; set; }
        public virtual test test { get; set; }
    }
}
