//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace test
{
    using System;
    using System.Collections.Generic;
    
    public partial class applicant
    {
        public int ap_ID { get; set; }
        public string ap_FirstName { get; set; }
        public string ap_LastName { get; set; }
        public string ap_email { get; set; }
        public string ap_contact { get; set; }
        public string ap_Summary { get; set; }
    }
}
