//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace test
{
    using System;
    using System.Collections.Generic;
    
    public partial class aps_change
    {
        public int apsc_ID { get; set; }
        public System.DateTime apsc_date { get; set; }
        public Nullable<int> as_ID { get; set; }
        public Nullable<int> app_ID { get; set; }
    
        public virtual app_status app_status { get; set; }
        public virtual application_ application_ { get; set; }
    }
}
