//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace test
{
    using System;
    using System.Collections.Generic;
    
    public partial class interview
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public interview()
        {
            this.interview_note = new HashSet<interview_note>();
        }
    
        public int I_ID { get; set; }
        public System.DateTime I_start_time { get; set; }
        public System.DateTime I_end_time { get; set; }
        public Nullable<int> app_ID { get; set; }
    
        public virtual application_ application_ { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<interview_note> interview_note { get; set; }
    }
}
