//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace test
{
    using System;
    using System.Collections.Generic;
    
    public partial class job
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public job()
        {
            this.application_ = new HashSet<application_>();
        }
    
        public int Job_ID { get; set; }
        public string Job_code { get; set; }
        public string Job_Name { get; set; }
        public string Job_description { get; set; }
        public System.DateTime Job_publish_date { get; set; }
        public int Job_Vacancies { get; set; }
        public Nullable<int> jc_Id { get; set; }
        public Nullable<int> jd_ID { get; set; }
        public Nullable<int> jo_ID { get; set; }
        public Nullable<int> p_ID { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<application_> application_ { get; set; }
        public virtual job_category job_category { get; set; }
        public virtual job_department job_department { get; set; }
        public virtual job_orgy job_orgy { get; set; }
        public virtual process process { get; set; }
    }
}
