//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace test
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class E_Project_2Entities : DbContext
    {
        public E_Project_2Entities()
            : base("name=E_Project_2Entities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Answer> Answers { get; set; }
        public virtual DbSet<ap_evaluate> ap_evaluate { get; set; }
        public virtual DbSet<app_document> app_document { get; set; }
        public virtual DbSet<app_status> app_status { get; set; }
        public virtual DbSet<app_test> app_test { get; set; }
        public virtual DbSet<applicant> applicants { get; set; }
        public virtual DbSet<application_> application_ { get; set; }
        public virtual DbSet<aps_change> aps_change { get; set; }
        public virtual DbSet<document> documents { get; set; }
        public virtual DbSet<interview> interviews { get; set; }
        public virtual DbSet<interview_note> interview_note { get; set; }
        public virtual DbSet<job> jobs { get; set; }
        public virtual DbSet<job_category> job_category { get; set; }
        public virtual DbSet<job_department> job_department { get; set; }
        public virtual DbSet<job_orgy> job_orgy { get; set; }
        public virtual DbSet<process> processes { get; set; }
        public virtual DbSet<process_step> process_step { get; set; }
        public virtual DbSet<Recruiter> Recruiters { get; set; }
        public virtual DbSet<Register> Registers { get; set; }
        public virtual DbSet<step> steps { get; set; }
        public virtual DbSet<test> tests { get; set; }
    }
}
