//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace test
{
    using System;
    using System.Collections.Generic;
    
    public partial class Register
    {
        public int reg_ID { get; set; }
        public string U_username { get; set; }
        public string U_fullname { get; set; }
        public string U_email { get; set; }
        public string U_password { get; set; }
        public string U_designation { get; set; }
    }
}
